/** Standard resources: generated by provinces, usable by any country (including AI). */
export type ResourceType =
  | "supplies"
  | "components"
  | "fuel"
  | "electronics"
  | "rareMaterials"
  | "manpower"
  | "money";

export type ResourceAmounts = Partial<Record<ResourceType, number>>;
